
#include <Arduino.h>
const String WEB = ""
"<!DOCTYPE html>"
"<html><head><title>PEG</title>"
"<meta name='mobile-web-app-capable' content='yes' />"
"<meta name='viewport' content='width=device-width' />"
"<style type=\"text/css\">"      
"#menus {display: inline-block;width: 100\%;height: 20\%;font-size: 3rem;box-sizing: border-box;}"
"html,body {font-family: 'Roboto', cursive;margin: 0;padding: 0;width: 100\%;height: 100\%;overflow: hidden;}"
".but {width: calc(100% / 5);float: left;text-align: center;color: white;}"
"#b1,#b3,#b5 {height: 100%;background-color: black;}"
"#b2,#b4 {height: 100%;background-color: #0a0a0a;}"
"</style><script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head>"
"<body><canvas id='colorspace'></canvas><div id=\"menus\">"
"<div class=\"but\" onclick=\"f1()\" id=\"b1\">Brightning</div>"
"<div class=\"but\" onclick=\"f2()\" id=\"b2\">Twilling</div>"
"<div class=\"but\" onclick=\"f3()\" id=\"b3\">Fade</div>"
"<div class=\"but\" onclick=\"f4()\" id=\"b4\">Rainbow</div>"
"<div class=\"but\" onclick=\"f5()\" id=\"b5\">Police</div>"
"</div><script type=\"text/javascript\">(function() {window['__CF$cv$params'] = {r: '6d73f9d99e1a3875',"
"m: 'JO2It2wfsSXyCB1OFPAoD8Qd4x905PaQUm.C63CrMpM-1643810743-0-Ab94tmya4ixItC/EdgOd7LB7Dd29HMbWGP2R9MOLbE+bMZ/9EWwoGhB8M/KfEvH9vlucUucllw4IDsUK+W1/XYv+bHSkVUsz0vwOhEXvuKJmdKr28wwq4c2o7400kjeCTzEUuYIgIOS4OYk4EiBzFtpA4ex79GnMr8yTGj6tj8ilCzpgQghhVh0UodpZeTPPsQ==',"
"s: [0x6ec53dab7b, 0x60b86451b1],}})();</script></body>"
"<script type='text/javascript'>var r = 0;var g = 0;var b = 0;var mode = 1;"
"(function() {var canvas = document.getElementById('colorspace');var ctx = canvas.getContext('2d');"
"function drawCanvas() {var colours = ctx.createLinearGradient(0, 0, window.innerWidth, 0);"
"for (var i = 0; i <= 360; i += 10) {colours.addColorStop(i / 360, 'hsl(' + i + ', 100%, 50%)');}"
"ctx.fillStyle = colours;ctx.fillRect(0, 0, window.innerWidth, window.innerHeight);"
"var luminance = ctx.createLinearGradient(0, 0, 0, ctx.canvas.height);"
"luminance.addColorStop(0, '#ffffff');"
"luminance.addColorStop(0.05, '#ffffff');"
"luminance.addColorStop(0.5, 'rgba(0,0,0,0)');"
"luminance.addColorStop(0.95, '#000000');"
"luminance.addColorStop(1, '#000000');"
"ctx.fillStyle = luminance;"
"ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);}"
"var eventLocked = false;"
"function handleEvent(clientX, clientY) {if (eventLocked) {return;}function colourCorrect(v) {return Math.round((v * v) / 256);}"
"var data = ctx.getImageData(clientX, clientY, 1, 1).data;"
"r = colourCorrect(data[0]);"
"g = colourCorrect(data[1]);"
"b = colourCorrect(data[2]);"
"sendREQUEST();}"
"canvas.addEventListener('click', function(event) {handleEvent(event.clientX, event.clientY, true);}, false);"
"canvas.addEventListener('touchmove', function(event) {handleEvent(event.touches[0].clientX, event.touches[0].clientY);}, false);"
"function resizeCanvas() {canvas.width = window.innerWidth;canvas.height = window.innerHeight * 0.8;drawCanvas();}"
"window.addEventListener('resize', resizeCanvas, false);resizeCanvas();drawCanvas();"
"document.ontouchmove = function(e) {e.preventDefault()};})();"
"function f1() {mode = 1;sendREQUEST();}"
"function f2() {mode = 2;sendREQUEST();}"
"function f3() {mode = 3;sendREQUEST();}"
"function f4() {mode = 4;sendREQUEST();}"
"function f5() {mode = 5;sendREQUEST();}"
"function sendREQUEST() {var req = new XMLHttpRequest();var params = ['r=' + r,'g=' + g,'b=' + b,'m=' + mode].join('&');"
"req.open('POST', '?' + params, true);req.send();eventLocked = true;"
"req.onreadystatechange = function() {if (req.readyState == 4) {eventLocked = false;}}}</script></html>";